/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DpAmbulanceWlList {
    }
}
declare global {
    interface HTMLDpAmbulanceWlListElement extends Components.DpAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLDpAmbulanceWlListElement: {
        prototype: HTMLDpAmbulanceWlListElement;
        new (): HTMLDpAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "dp-ambulance-wl-list": HTMLDpAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface DpAmbulanceWlList {
    }
    interface IntrinsicElements {
        "dp-ambulance-wl-list": DpAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dp-ambulance-wl-list": LocalJSX.DpAmbulanceWlList & JSXBase.HTMLAttributes<HTMLDpAmbulanceWlListElement>;
        }
    }
}
